apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fleetmsv2
  name: fleetmsv2
spec:
  ports:
    - name: 8082-8082
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: fleetmsv2
  type: ClusterIP
status:
  loadBalancer: {}
