apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fleetmsv2
  name: fleetmsv2
spec:
  ports:
    - name: 8081-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: fleetmsv2
  type: ClusterIP
status:
  loadBalancer: {}
